// <auto-generated />
using System;
using MasterNet.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterNet.Persistence.Migrations
{
    [DbContext(typeof(MasterNetDbContext))]
    [Migration("20240509212134_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.2.24128.4");

            modelBuilder.Entity("MasterNet.Domain.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alumno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Puntaje")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("calificacion", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPulicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cursos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("da315308-c277-4ea4-814b-ef5ef0231201"),
                            Descripcion = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6724),
                            Titulo = "Practical Cotton Mouse"
                        },
                        new
                        {
                            Id = new Guid("34858352-ac85-4971-92a4-4e88d42561b9"),
                            Descripcion = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6782),
                            Titulo = "Intelligent Metal Car"
                        },
                        new
                        {
                            Id = new Guid("0cbce446-414a-4fec-91e2-4dcd6665d176"),
                            Descripcion = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6800),
                            Titulo = "Tasty Granite Computer"
                        },
                        new
                        {
                            Id = new Guid("f8dfd787-f9c1-4b5c-8f1a-59d535217f17"),
                            Descripcion = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6817),
                            Titulo = "Unbranded Steel Shirt"
                        },
                        new
                        {
                            Id = new Guid("7e4e0d83-3f62-4dd9-9eba-5ba9fb6ee8d3"),
                            Descripcion = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6851),
                            Titulo = "Licensed Metal Bacon"
                        },
                        new
                        {
                            Id = new Guid("ab978782-7a60-4d2e-9d5e-10b5112b77e1"),
                            Descripcion = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6868),
                            Titulo = "Licensed Frozen Shoes"
                        },
                        new
                        {
                            Id = new Guid("2323ced8-6d79-4aa0-a2d6-7b86b47a0195"),
                            Descripcion = "The Football Is Good For Training And Recreational Purposes",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6885),
                            Titulo = "Awesome Fresh Chips"
                        },
                        new
                        {
                            Id = new Guid("6f2faf78-dc69-4206-a73f-f8d31d407b88"),
                            Descripcion = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6909),
                            Titulo = "Rustic Metal Sausages"
                        },
                        new
                        {
                            Id = new Guid("76390a1a-c075-43f6-b4c3-23400b2cf77f"),
                            Descripcion = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            FechaPulicacion = new DateTime(2024, 5, 9, 15, 21, 34, 359, DateTimeKind.Local).AddTicks(6925),
                            Titulo = "Gorgeous Plastic Mouse"
                        });
                });

            modelBuilder.Entity("MasterNet.Domain.CursoInstructor", b =>
                {
                    b.Property<Guid>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.HasKey("InstructorId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("cursos_instructores", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.CursoPrecio", b =>
                {
                    b.Property<Guid>("PrecioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.HasKey("PrecioId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("cursos_precios", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("instructores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("168a059c-591a-4b17-ba07-add6c60f147a"),
                            Apellidos = "Grady",
                            Grado = "Regional Paradigm Technician",
                            Nombre = "Cameron"
                        },
                        new
                        {
                            Id = new Guid("974be9c1-0887-4372-b712-804b58e209c5"),
                            Apellidos = "Heathcote",
                            Grado = "Direct Mobility Assistant",
                            Nombre = "Zachery"
                        },
                        new
                        {
                            Id = new Guid("da0bdc2c-44ac-4357-a4ea-36279efa2cdb"),
                            Apellidos = "Dickens",
                            Grado = "Product Accountability Supervisor",
                            Nombre = "Lily"
                        },
                        new
                        {
                            Id = new Guid("e49859c1-123d-4c8a-97c7-f9505bfb3d67"),
                            Apellidos = "Lubowitz",
                            Grado = "Product Creative Planner",
                            Nombre = "Estelle"
                        },
                        new
                        {
                            Id = new Guid("c497f33e-07a8-4e0a-8359-71a4092efbf6"),
                            Apellidos = "Ritchie",
                            Grado = "Direct Applications Executive",
                            Nombre = "Caterina"
                        },
                        new
                        {
                            Id = new Guid("9517ece1-2922-4af2-817a-29cd2f5a31b3"),
                            Apellidos = "Sawayn",
                            Grado = "Internal Intranet Executive",
                            Nombre = "Curtis"
                        },
                        new
                        {
                            Id = new Guid("919b0584-4891-4fe3-a199-f5723b0d12dd"),
                            Apellidos = "Homenick",
                            Grado = "Corporate Paradigm Producer",
                            Nombre = "Terrance"
                        },
                        new
                        {
                            Id = new Guid("47542d32-08f7-4805-9c1c-5528b3c633a0"),
                            Apellidos = "O'Reilly",
                            Grado = "Internal Solutions Liaison",
                            Nombre = "Art"
                        },
                        new
                        {
                            Id = new Guid("cad838b8-7265-4e03-bddd-40be360587f2"),
                            Apellidos = "Howe",
                            Grado = "National Configuration Analyst",
                            Nombre = "Evalyn"
                        },
                        new
                        {
                            Id = new Guid("09285e18-d0c2-4543-bc07-1a2c063a5e9d"),
                            Apellidos = "Klein",
                            Grado = "Regional Tactics Strategist",
                            Nombre = "Ewald"
                        });
                });

            modelBuilder.Entity("MasterNet.Domain.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("imagenes", (string)null);
                });

            modelBuilder.Entity("MasterNet.Domain.Precio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal?>("PrecioActual")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecioPromocion")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("precios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("efd92fc1-1991-4137-b945-dc49c86fdba2"),
                            Nombre = "Precio Regular",
                            PrecioActual = 10.0m,
                            PrecioPromocion = 8.0m
                        });
                });

            modelBuilder.Entity("MasterNet.Domain.Calificacion", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("Calificaciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("MasterNet.Domain.CursoInstructor", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("CursoInstructores")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterNet.Domain.Instructor", "Instructor")
                        .WithMany("CursosInstructores")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("MasterNet.Domain.CursoPrecio", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("CursoPrecios")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterNet.Domain.Precio", "Precio")
                        .WithMany("CursosPrecios")
                        .HasForeignKey("PrecioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Precio");
                });

            modelBuilder.Entity("MasterNet.Domain.Photo", b =>
                {
                    b.HasOne("MasterNet.Domain.Curso", "Curso")
                        .WithMany("Photos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("MasterNet.Domain.Curso", b =>
                {
                    b.Navigation("Calificaciones");

                    b.Navigation("CursoInstructores");

                    b.Navigation("CursoPrecios");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MasterNet.Domain.Instructor", b =>
                {
                    b.Navigation("CursosInstructores");
                });

            modelBuilder.Entity("MasterNet.Domain.Precio", b =>
                {
                    b.Navigation("CursosPrecios");
                });
#pragma warning restore 612, 618
        }
    }
}
